CREATE DATABASE IF NOT EXISTS skladb
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'fwnolikt'@'localhost' IDENTIFIED BY 'fwnolikt_demo';
CREATE USER IF NOT EXISTS 'fwnolikt'@'127.0.0.1' IDENTIFIED BY 'fwnolikt_demo';

GRANT ALL PRIVILEGES ON skladb.* TO 'fwnolikt'@'localhost';
GRANT ALL PRIVILEGES ON skladb.* TO 'fwnolikt'@'127.0.0.1';

USE skladb;

CREATE TABLE IF NOT EXISTS UNT_EXPORT (
  ID INT NOT NULL AUTO_INCREMENT,
  ARTICLE VARCHAR(64) NOT NULL,
  NAME VARCHAR(255) NULL,
  QTY DECIMAL(12, 3) NULL,
  PRICE DECIMAL(12, 2) NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE KEY UX_UNT_EXPORT_ARTICLE (ARTICLE)
);

INSERT INTO UNT_EXPORT (ARTICLE, NAME, QTY, PRICE)
VALUES
  ('DEMO-001', 'Demo article 1', 10, 12.50),
  ('DEMO-002', 'Demo article 2', 5, 7.25)
ON DUPLICATE KEY UPDATE
  NAME = VALUES(NAME),
  QTY = VALUES(QTY),
  PRICE = VALUES(PRICE);

DROP PROCEDURE IF EXISTS UNT_GET_ARTICLE_ID_BY_ARTICLE;
DROP PROCEDURE IF EXISTS UNT_UPSERT_ARTICLE;
DROP FUNCTION IF EXISTS UNT_ARTICLE_EXISTS;

DELIMITER //

CREATE PROCEDURE UNT_GET_ARTICLE_ID_BY_ARTICLE(
  IN P_ARTICLE VARCHAR(64),
  OUT P_ID INT
)
BEGIN
  SELECT ID INTO P_ID
  FROM UNT_EXPORT
  WHERE ARTICLE = P_ARTICLE
  LIMIT 1;
END//

CREATE PROCEDURE UNT_UPSERT_ARTICLE(
  IN P_ARTICLE VARCHAR(64),
  IN P_NAME VARCHAR(255),
  IN P_QTY DECIMAL(12, 3),
  IN P_PRICE DECIMAL(12, 2),
  OUT P_ID INT
)
BEGIN
  INSERT INTO UNT_EXPORT (ARTICLE, NAME, QTY, PRICE)
  VALUES (P_ARTICLE, P_NAME, P_QTY, P_PRICE)
  ON DUPLICATE KEY UPDATE
    NAME = VALUES(NAME),
    QTY = VALUES(QTY),
    PRICE = VALUES(PRICE);

  SELECT ID INTO P_ID
  FROM UNT_EXPORT
  WHERE ARTICLE = P_ARTICLE
  LIMIT 1;
END//

CREATE FUNCTION UNT_ARTICLE_EXISTS(P_ARTICLE VARCHAR(64))
RETURNS INT
DETERMINISTIC
READS SQL DATA
BEGIN
  RETURN (
    SELECT COUNT(*)
    FROM UNT_EXPORT
    WHERE ARTICLE = P_ARTICLE
  );
END//

DELIMITER ;

FLUSH PRIVILEGES;
