[mysqld]
basedir=C:/FWNolikt/mysql-9.6.0-winx64
datadir=C:/FWNolikt/mysql-data
port=3307
bind-address=127.0.0.1
log-error=C:/FWNolikt/mysql-logs/mysql.err
pid-file=C:/FWNolikt/mysql-logs/mysql.pid

[client]
host=127.0.0.1
port=3307
user=root
